---
title: C6320 | Dokumentacja firmy Microsoft
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: cffb779f2b92cfee495480e2a1ba4946c5def605
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 11/16/2018
ms.locfileid: "51798121"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Ostrzeżenie C6320: wyrażenie filtru wyjątków jest stałą EXCEPTION_EXECUTE_HANDLER. To może maskować wyjątki, które nie zostały przeznaczone do obsługi  
  
 To ostrzeżenie wskazuje efekt uboczny użycia stałą EXCEPTION_EXECUTE_HANDLER w blokiem __except. W tym przypadku instrukcja w \_blok _except zawsze będą wykonywane do obsługi wyjątków, łącznie z wyjątkami, nie mają być obsługiwane w określonej funkcji. Zaleca się sprawdzenie, czy wyjątek przed jego obsługi.  
  
## <a name="example"></a>Przykład  
 Poniższy kod generuje to ostrzeżenie, ponieważ __except block będą próbować obsłużyć wyjątki wszystkich typów:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Aby poprawić to ostrzeżenie, użyj `GetExceptionCode` pod kątem określonego wyjątku, przed jej obsługi, jak pokazano w poniższym kodzie:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Zobacz też  
 [try-except, instrukcja](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



